# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/elhadjium007/Bureau/projet-tech-1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/elhadjium007/Bureau/projet-tech-1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/elhadjium007/Bureau/projet-tech-1/CMakeFiles /home/elhadjium007/Bureau/projet-tech-1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/elhadjium007/Bureau/projet-tech-1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) -f CMakeFiles/doc.dir/build.make CMakeFiles/doc.dir/build
.PHONY : doc/fast

#=============================================================================
# Target rules for targets named headers

# Build rule for target.
headers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 headers
.PHONY : headers

# fast build rule for target.
headers/fast:
	$(MAKE) -f CMakeFiles/headers.dir/build.make CMakeFiles/headers.dir/build
.PHONY : headers/fast

#=============================================================================
# Target rules for targets named ei

# Build rule for target.
ei: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ei
.PHONY : ei

# fast build rule for target.
ei/fast:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/build
.PHONY : ei/fast

#=============================================================================
# Target rules for targets named minimal

# Build rule for target.
minimal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 minimal
.PHONY : minimal

# fast build rule for target.
minimal/fast:
	$(MAKE) -f tests/CMakeFiles/minimal.dir/build.make tests/CMakeFiles/minimal.dir/build
.PHONY : minimal/fast

#=============================================================================
# Target rules for targets named frame

# Build rule for target.
frame: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 frame
.PHONY : frame

# fast build rule for target.
frame/fast:
	$(MAKE) -f tests/CMakeFiles/frame.dir/build.make tests/CMakeFiles/frame.dir/build
.PHONY : frame/fast

#=============================================================================
# Target rules for targets named test_draw_recursivite

# Build rule for target.
test_draw_recursivite: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_draw_recursivite
.PHONY : test_draw_recursivite

# fast build rule for target.
test_draw_recursivite/fast:
	$(MAKE) -f tests/CMakeFiles/test_draw_recursivite.dir/build.make tests/CMakeFiles/test_draw_recursivite.dir/build
.PHONY : test_draw_recursivite/fast

#=============================================================================
# Target rules for targets named button

# Build rule for target.
button: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 button
.PHONY : button

# fast build rule for target.
button/fast:
	$(MAKE) -f tests/CMakeFiles/button.dir/build.make tests/CMakeFiles/button.dir/build
.PHONY : button/fast

#=============================================================================
# Target rules for targets named unit_tests

# Build rule for target.
unit_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unit_tests
.PHONY : unit_tests

# fast build rule for target.
unit_tests/fast:
	$(MAKE) -f tests/CMakeFiles/unit_tests.dir/build.make tests/CMakeFiles/unit_tests.dir/build
.PHONY : unit_tests/fast

#=============================================================================
# Target rules for targets named toplevel

# Build rule for target.
toplevel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 toplevel
.PHONY : toplevel

# fast build rule for target.
toplevel/fast:
	$(MAKE) -f tests/CMakeFiles/toplevel.dir/build.make tests/CMakeFiles/toplevel.dir/build
.PHONY : toplevel/fast

#=============================================================================
# Target rules for targets named demo

# Build rule for target.
demo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 demo
.PHONY : demo

# fast build rule for target.
demo/fast:
	$(MAKE) -f tests/CMakeFiles/demo.dir/build.make tests/CMakeFiles/demo.dir/build
.PHONY : demo/fast

src/ei_application.o: src/ei_application.cpp.o

.PHONY : src/ei_application.o

# target to build an object file
src/ei_application.cpp.o:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_application.cpp.o
.PHONY : src/ei_application.cpp.o

src/ei_application.i: src/ei_application.cpp.i

.PHONY : src/ei_application.i

# target to preprocess a source file
src/ei_application.cpp.i:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_application.cpp.i
.PHONY : src/ei_application.cpp.i

src/ei_application.s: src/ei_application.cpp.s

.PHONY : src/ei_application.s

# target to generate assembly for a file
src/ei_application.cpp.s:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_application.cpp.s
.PHONY : src/ei_application.cpp.s

src/ei_button.o: src/ei_button.cpp.o

.PHONY : src/ei_button.o

# target to build an object file
src/ei_button.cpp.o:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_button.cpp.o
.PHONY : src/ei_button.cpp.o

src/ei_button.i: src/ei_button.cpp.i

.PHONY : src/ei_button.i

# target to preprocess a source file
src/ei_button.cpp.i:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_button.cpp.i
.PHONY : src/ei_button.cpp.i

src/ei_button.s: src/ei_button.cpp.s

.PHONY : src/ei_button.s

# target to generate assembly for a file
src/ei_button.cpp.s:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_button.cpp.s
.PHONY : src/ei_button.cpp.s

src/ei_button_radio.o: src/ei_button_radio.cpp.o

.PHONY : src/ei_button_radio.o

# target to build an object file
src/ei_button_radio.cpp.o:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_button_radio.cpp.o
.PHONY : src/ei_button_radio.cpp.o

src/ei_button_radio.i: src/ei_button_radio.cpp.i

.PHONY : src/ei_button_radio.i

# target to preprocess a source file
src/ei_button_radio.cpp.i:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_button_radio.cpp.i
.PHONY : src/ei_button_radio.cpp.i

src/ei_button_radio.s: src/ei_button_radio.cpp.s

.PHONY : src/ei_button_radio.s

# target to generate assembly for a file
src/ei_button_radio.cpp.s:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_button_radio.cpp.s
.PHONY : src/ei_button_radio.cpp.s

src/ei_check_box.o: src/ei_check_box.cpp.o

.PHONY : src/ei_check_box.o

# target to build an object file
src/ei_check_box.cpp.o:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_check_box.cpp.o
.PHONY : src/ei_check_box.cpp.o

src/ei_check_box.i: src/ei_check_box.cpp.i

.PHONY : src/ei_check_box.i

# target to preprocess a source file
src/ei_check_box.cpp.i:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_check_box.cpp.i
.PHONY : src/ei_check_box.cpp.i

src/ei_check_box.s: src/ei_check_box.cpp.s

.PHONY : src/ei_check_box.s

# target to generate assembly for a file
src/ei_check_box.cpp.s:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_check_box.cpp.s
.PHONY : src/ei_check_box.cpp.s

src/ei_draw.o: src/ei_draw.cpp.o

.PHONY : src/ei_draw.o

# target to build an object file
src/ei_draw.cpp.o:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_draw.cpp.o
.PHONY : src/ei_draw.cpp.o

src/ei_draw.i: src/ei_draw.cpp.i

.PHONY : src/ei_draw.i

# target to preprocess a source file
src/ei_draw.cpp.i:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_draw.cpp.i
.PHONY : src/ei_draw.cpp.i

src/ei_draw.s: src/ei_draw.cpp.s

.PHONY : src/ei_draw.s

# target to generate assembly for a file
src/ei_draw.cpp.s:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_draw.cpp.s
.PHONY : src/ei_draw.cpp.s

src/ei_entry.o: src/ei_entry.cpp.o

.PHONY : src/ei_entry.o

# target to build an object file
src/ei_entry.cpp.o:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_entry.cpp.o
.PHONY : src/ei_entry.cpp.o

src/ei_entry.i: src/ei_entry.cpp.i

.PHONY : src/ei_entry.i

# target to preprocess a source file
src/ei_entry.cpp.i:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_entry.cpp.i
.PHONY : src/ei_entry.cpp.i

src/ei_entry.s: src/ei_entry.cpp.s

.PHONY : src/ei_entry.s

# target to generate assembly for a file
src/ei_entry.cpp.s:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_entry.cpp.s
.PHONY : src/ei_entry.cpp.s

src/ei_eventmanager.o: src/ei_eventmanager.cpp.o

.PHONY : src/ei_eventmanager.o

# target to build an object file
src/ei_eventmanager.cpp.o:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_eventmanager.cpp.o
.PHONY : src/ei_eventmanager.cpp.o

src/ei_eventmanager.i: src/ei_eventmanager.cpp.i

.PHONY : src/ei_eventmanager.i

# target to preprocess a source file
src/ei_eventmanager.cpp.i:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_eventmanager.cpp.i
.PHONY : src/ei_eventmanager.cpp.i

src/ei_eventmanager.s: src/ei_eventmanager.cpp.s

.PHONY : src/ei_eventmanager.s

# target to generate assembly for a file
src/ei_eventmanager.cpp.s:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_eventmanager.cpp.s
.PHONY : src/ei_eventmanager.cpp.s

src/ei_frame.o: src/ei_frame.cpp.o

.PHONY : src/ei_frame.o

# target to build an object file
src/ei_frame.cpp.o:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_frame.cpp.o
.PHONY : src/ei_frame.cpp.o

src/ei_frame.i: src/ei_frame.cpp.i

.PHONY : src/ei_frame.i

# target to preprocess a source file
src/ei_frame.cpp.i:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_frame.cpp.i
.PHONY : src/ei_frame.cpp.i

src/ei_frame.s: src/ei_frame.cpp.s

.PHONY : src/ei_frame.s

# target to generate assembly for a file
src/ei_frame.cpp.s:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_frame.cpp.s
.PHONY : src/ei_frame.cpp.s

src/ei_geometry_manager.o: src/ei_geometry_manager.cpp.o

.PHONY : src/ei_geometry_manager.o

# target to build an object file
src/ei_geometry_manager.cpp.o:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_geometry_manager.cpp.o
.PHONY : src/ei_geometry_manager.cpp.o

src/ei_geometry_manager.i: src/ei_geometry_manager.cpp.i

.PHONY : src/ei_geometry_manager.i

# target to preprocess a source file
src/ei_geometry_manager.cpp.i:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_geometry_manager.cpp.i
.PHONY : src/ei_geometry_manager.cpp.i

src/ei_geometry_manager.s: src/ei_geometry_manager.cpp.s

.PHONY : src/ei_geometry_manager.s

# target to generate assembly for a file
src/ei_geometry_manager.cpp.s:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_geometry_manager.cpp.s
.PHONY : src/ei_geometry_manager.cpp.s

src/ei_internals_calbacks.o: src/ei_internals_calbacks.cpp.o

.PHONY : src/ei_internals_calbacks.o

# target to build an object file
src/ei_internals_calbacks.cpp.o:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_internals_calbacks.cpp.o
.PHONY : src/ei_internals_calbacks.cpp.o

src/ei_internals_calbacks.i: src/ei_internals_calbacks.cpp.i

.PHONY : src/ei_internals_calbacks.i

# target to preprocess a source file
src/ei_internals_calbacks.cpp.i:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_internals_calbacks.cpp.i
.PHONY : src/ei_internals_calbacks.cpp.i

src/ei_internals_calbacks.s: src/ei_internals_calbacks.cpp.s

.PHONY : src/ei_internals_calbacks.s

# target to generate assembly for a file
src/ei_internals_calbacks.cpp.s:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_internals_calbacks.cpp.s
.PHONY : src/ei_internals_calbacks.cpp.s

src/ei_toplevel.o: src/ei_toplevel.cpp.o

.PHONY : src/ei_toplevel.o

# target to build an object file
src/ei_toplevel.cpp.o:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_toplevel.cpp.o
.PHONY : src/ei_toplevel.cpp.o

src/ei_toplevel.i: src/ei_toplevel.cpp.i

.PHONY : src/ei_toplevel.i

# target to preprocess a source file
src/ei_toplevel.cpp.i:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_toplevel.cpp.i
.PHONY : src/ei_toplevel.cpp.i

src/ei_toplevel.s: src/ei_toplevel.cpp.s

.PHONY : src/ei_toplevel.s

# target to generate assembly for a file
src/ei_toplevel.cpp.s:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_toplevel.cpp.s
.PHONY : src/ei_toplevel.cpp.s

src/ei_widget.o: src/ei_widget.cpp.o

.PHONY : src/ei_widget.o

# target to build an object file
src/ei_widget.cpp.o:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_widget.cpp.o
.PHONY : src/ei_widget.cpp.o

src/ei_widget.i: src/ei_widget.cpp.i

.PHONY : src/ei_widget.i

# target to preprocess a source file
src/ei_widget.cpp.i:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_widget.cpp.i
.PHONY : src/ei_widget.cpp.i

src/ei_widget.s: src/ei_widget.cpp.s

.PHONY : src/ei_widget.s

# target to generate assembly for a file
src/ei_widget.cpp.s:
	$(MAKE) -f CMakeFiles/ei.dir/build.make CMakeFiles/ei.dir/src/ei_widget.cpp.s
.PHONY : src/ei_widget.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... doc"
	@echo "... headers"
	@echo "... ei"
	@echo "... minimal"
	@echo "... frame"
	@echo "... test_draw_recursivite"
	@echo "... button"
	@echo "... unit_tests"
	@echo "... toplevel"
	@echo "... demo"
	@echo "... src/ei_application.o"
	@echo "... src/ei_application.i"
	@echo "... src/ei_application.s"
	@echo "... src/ei_button.o"
	@echo "... src/ei_button.i"
	@echo "... src/ei_button.s"
	@echo "... src/ei_button_radio.o"
	@echo "... src/ei_button_radio.i"
	@echo "... src/ei_button_radio.s"
	@echo "... src/ei_check_box.o"
	@echo "... src/ei_check_box.i"
	@echo "... src/ei_check_box.s"
	@echo "... src/ei_draw.o"
	@echo "... src/ei_draw.i"
	@echo "... src/ei_draw.s"
	@echo "... src/ei_entry.o"
	@echo "... src/ei_entry.i"
	@echo "... src/ei_entry.s"
	@echo "... src/ei_eventmanager.o"
	@echo "... src/ei_eventmanager.i"
	@echo "... src/ei_eventmanager.s"
	@echo "... src/ei_frame.o"
	@echo "... src/ei_frame.i"
	@echo "... src/ei_frame.s"
	@echo "... src/ei_geometry_manager.o"
	@echo "... src/ei_geometry_manager.i"
	@echo "... src/ei_geometry_manager.s"
	@echo "... src/ei_internals_calbacks.o"
	@echo "... src/ei_internals_calbacks.i"
	@echo "... src/ei_internals_calbacks.s"
	@echo "... src/ei_toplevel.o"
	@echo "... src/ei_toplevel.i"
	@echo "... src/ei_toplevel.s"
	@echo "... src/ei_widget.o"
	@echo "... src/ei_widget.i"
	@echo "... src/ei_widget.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

